FROM ubuntu:22.04

ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update && apt-get install -y \
    ansible \
    openssh-client \
    python3 \
    python3-pip

CMD ["sh", "-c", "tail -f /dev/null"]
